# This is the leaderboard style, this leaderboard will be used
# when the entity that is being monitored killed
# Styles:
# - SHOW_ALL: Show all players that contribute on damaging the entity (you can set the max position that will be shown too)
#             Placeholders:
#             - {position} to show the position on the leaderboard
#             - {player} return the player's name
#             - {damage} return the damage that player dealt
# - SHOW_SPECIFIC: Show only specific position that get broadcasted that are defined on the config
#             Placeholders:
#             - {player_x} to show specific position player's name (see example below!)
#             - {damage_x} to show specific position damage dealt (see example below!)
leaderboardStyle:
  type: SHOW_ALL
  centerMessage: true
  SHOW_ALL:
    maxPosition: 10 # Set 0 to disable
    header:
      - "&6&m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      - ""
    format: "&6{position}. &e{player} &fdeals &a{damage} damage"
    footer:
      - ""
      - "&6&m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  SHOW_SPECIFIC:
    playerNotFound: "&7None"
    damageNotFound: "&a0"
    messages:
      - "&6&m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
      - "&75 Top Damager Leaderboard"
      - ""
      - " &61. &e{player_1} &fdeals &a{damage_1} damage"
      - " &62. &e{player_2} &fdeals &a{damage_2} damage"
      - " &63. &e{player_3} &fdeals &a{damage_3} damage"
      - " &64. &e{player_4} &fdeals &a{damage_4} damage"
      - " &65. &e{player_5} &fdeals &a{damage_5} damage"
      - ""
      - "&6&m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

messages:
  noPermission: "&cYou don't have permission to use this command!"
  reload: "&aYou have reloaded the configuration!"